protected/models/Articles.php
<?php

/**
 * This is the model class for table "articles".
 *
 * The followings are the available columns in table 'articles':
 * @property string $id
 * @property string $idcategory
 * @property string $alias
 * @property string $htitl_uk
 * @property string $htitl_ru
 * @property string $hdesc_uk
 * @property string $hdesc_ru
 * @property string $hkeyw_uk
 * @property string $hkeyw_ru
 * @property string $name_uk
 * @property string $name_ru
 * @property string $anons_uk
 * @property string $anons_ru
 * @property string $content_uk
 * @property string $content_ru
 * @property string $bannerlink
 * @property integer $timecreate
 * @property integer $timeupdate
 * @property integer $status
 */
class Articles extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'articles';
	}
	
	public $image_sliderBg;
	public $image_slider;
	public $image;
 
 	public function behaviors(){
    return array(
      'imageBehavior' => array(
        'class' => 'ImageBehavior',
        'imagePath' => '/images/articles/',
        'imageField' => 'image',
        'imageFolderName' => 'articles',
      ),
    );
  }
	
	public function beforeSave(){
		if(parent::beforeSave())
    {
    	$this->setAttribute('timework', CDates::toUnixDate($this->timework));
			if($this->isNewRecord){
				$this->setAttribute('timecreate', TIME);
				$this->setAttribute('timeupdate', TIME);
				$this->setAttribute('sort', 0);
			} else{
				$this->setAttribute('timeupdate', TIME);
			}
			
			return true;
    }
    else
        return false;
	}
	
	public function afterSave(){
		parent::afterSave();
    
    if ($this->isNewRecord) {
			//Update sort in All Rows
			$connection=Yii::app()->db;
			$sql="UPDATE {$this->tableName()} set sort=sort+1";
			$command=$connection->createCommand($sql)->execute();
    }
    
    //Upload picture
    $this->image=CUploadedFile::getInstance($this,'image');
		if($this->image){
			$imagePath = $this->getPhotoNamePath($this->id.'.jpg');
			$this->image->saveAs($imagePath);
		}
		//Upload image_sliderBg
		$this->image_sliderBg=CUploadedFile::getInstance($this,'image_sliderBg');
		if($this->image_sliderBg){
			$imagePath = $this->getPhotoNamePath($this->id.'.sBg.jpg');
			$this->image_sliderBg->saveAs($imagePath);
		}
		//Upload image_slider
    $this->image_slider=CUploadedFile::getInstance($this,'image_slider');
		if($this->image_slider){
			$imagePath = $this->getPhotoNamePath($this->id.'.s.jpg');
			$this->image_slider->saveAs($imagePath);
		}

	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name_ru, name2_ru, alias', 'required'),
			array('status, onslider, views, id_author', 'numerical', 'integerOnly'=>true),
			array('alias, htitl_ru, hdesc_ru, hkeyw_ru, name_ru', 'length', 'max'=>256),
			array('timecreate, timeupdate, timework', 'length', 'max'=>10),
			array('views', 'length', 'max'=>11),
			array('anons_ru, content_ru', 'safe'),
			array('alias', 'unique', 'className' => 'Articles', 'message' => 'This alias is already in database'),
			array('alias', 'match', 'pattern' => '/^[a-z0-9_\-]+$/u', 'message' => "Incorrect symbols. Allow only small english letters and numbers"),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, idcategory, alias, htitl_uk, htitl_ru, hdesc_uk, hdesc_ru, hkeyw_uk, hkeyw_ru, name_uk, name_ru, name2_ru, anons_uk, anons_ru, content_uk, content_ru, timecreate, timeupdate, timework, status, onslider,views', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'articlesCategory0' => array(self::HAS_ONE, 'ArticlesCategory', array('id'=>'idcategory')),
			'articlesAuthor' => array(self::HAS_ONE, 'Authors', array('id'=>'id_author')),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'alias' => 'Урл',
			'id_category' => 'Категория',
			'id_author' => 'Автор',
			'htitl_ru' => 'Метатег Title',
			'hdesc_ru' => 'Метатег Description',
			'hkeyw_ru' => 'Метатег Keywords',
			'name_ru' => 'Имя',
			'name2_ru' => 'Описание',
			'anons_ru' => 'Анонс',
			'content_ru' => 'Контент',
			'timecreate' => 'Timecreate',
			'timeupdate' => 'Timeupdate',
			'timework' => 'Дата начала',
			'status' => 'Статус',
			'onslider' => 'На_главную (статус)',
			'views' => 'Просмотры',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('alias',$this->alias,true);
		$criteria->compare('htitl_ru',$this->htitl_ru,true);
		$criteria->compare('hdesc_ru',$this->hdesc_ru,true);
		$criteria->compare('hkeyw_ru',$this->hkeyw_ru,true);
		$criteria->compare('name_ru',$this->name_ru,true);
		$criteria->compare('anons_ru',$this->anons_ru,true);
		$criteria->compare('content_ru',$this->content_ru,true);
		$criteria->compare('timecreate',$this->timecreate,true);
		$criteria->compare('timeupdate',$this->timeupdate,true);
		$criteria->compare('status',$this->status);
		$criteria->compare('onslider',$this->onslider);
		$criteria->compare('views',$this->views);
		$criteria->compare('id_author',$this->id_author);
		if(!isset($_GET['Articles_sort'])){
			$criteria->order = 'timework DESC';	
		}

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Articles the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ArticlesController.php
<?php

class ArticlesController extends CFrontend
{
	/**
	* Displays a particular model.
	* @param integer $id the ID of the model to be displayed
	*/
	public function actionView($alias=false)
	{
		//$model = Articles::model()->find('alias=:alias AND status=1', array('alias'=>$alias));		
		$model = Articles::model()->find('alias=:alias', array('alias'=>$alias));		
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		
		//Add views
		$connection=Yii::app()->db;
		$sql="UPDATE {$model->tableName()} set views=views+1 WHERE id=".(int)$model->id."";
		if($command=$connection->createCommand($sql)->execute()){
			$model->views++; 	
		}
		
			
		//$otherArticles = Articles::model()->findAll('id!=:id AND status=1', array('id'=>$model->id));		
		//Meta
		Yii::app()->clientScript->registerMetaTag($model->{'hdesc'.DMultilangHelper::getPrefix()}, 'description');
		Yii::app()->clientScript->registerMetaTag($model->{'hkeyw'.DMultilangHelper::getPrefix()}, 'keywords');
		$this->pageTitle = $model->{'htitl'.DMultilangHelper::getPrefix()};	
		
		$photosModel = new Photos('search');	
		$photosModel->unsetAttributes();
		
		$this->render('view',array(
			'model'=>$model,
			//'otherArticles'=>$otherArticles,
			'photoList'=>$photosModel->findAll('type="article" AND id_parent='.$model->id.' AND status=1 ORDER BY sort ASC'),
		));
	}

	/**
	* Lists all models.
	*/
	public function actionIndex()
	{
		$criteria = new CDbCriteria;
		$criteria->condition = 't.status=:active';
		$criteria->params = array('active'=>1);
		
		//If Search
		if(isset($_GET['searcharticlesname'])){
			$criteria->addCondition("t.hkeyw_ru LIKE :name OR t.name_ru LIKE :name OR t.name2_ru LIKE :name");//hkeyw_ru,name_ru,name2_ru
			$criteria->params = $criteria->params + array('name'=>"%{$_GET['searcharticlesname']}%");
		}
		
		$criteria->order = 'timework desc';
		$dataProvider=new CActiveDataProvider('Articles', array(
		    'criteria'=>$criteria,
		    'countCriteria'=>$criteria,
		    'pagination'=>array(
		    	'pageSize'=>6,
		    )
		  ));
		
		//$dataProvider=new CActiveDataProvider('Articles');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}
	

	/**
	* Returns the data model based on the primary key given in the GET variable.
	* If the data model is not found, an HTTP exception will be raised.
	* @param integer the ID of the model to be loaded
	*/
	public function loadModel($id)
	{
		$model=Articles::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

}

protected/views/articles/_view.php
<div class="blog-item m-bot-35 clearfix">
	<div class="hover-item">
		<div class="clearfix">
			<div class="blog-item-date-inf-container left">
				<?php if($data->id != 1){ ?>
				<div class="blog-item-date-cont">
					<div class="blog-item-date"><?=date('d',$data->timework);?></div>
					<div class="blog-item-mounth"><?=CDates::getMounthMini(date('n',$data->timework));?></div>
				</div>
				<?php } ?>
				<div>
					<div class="blog-item-category-img">
						<img src="/images/icon-standart-post.png" alt="Ipsum" >
					</div>
				</div>
			</div>

			<div class="view view-first">				
				<?php if($img = $data->getPhotoNameUrl($data->id.'.jpg', $data->timeupdate)){ ?>						
					<a href="<?=$this->createUrl('/articles/view',array('alias'=>$data->alias));?>">
						<img src="<?=$img;?>" alt="<?php echo $data->{'name'.DMultilangHelper::getPrefix()};?>" style="width:100%" >					
						<div class="mask"></div>
					</a>
				<?php } ?>					
				
				<?php /*
				<div class="abs">
					<a href="<?=$this->createUrl('/articles/view',array('alias'=>$data->alias));?>" class="lightbox zoom info"></a><a href="<?=$this->createUrl('/articles/view',array('alias'=>$data->alias));?>" class="link info"></a>
				</div>	*/?>
			</div>
		</div>	
		<div class="blog-item-caption-container">
			<a class="a-invert" href="<?=$this->createUrl('/articles/view',array('alias'=>$data->alias));?>" ><span class="bold"><?php echo $data->{'name'.DMultilangHelper::getPrefix()};?></span> <?php echo $data->{'name2'.DMultilangHelper::getPrefix()};?></a>
			<div class="lp-item-container-border clearfix">
				<div class="blog-info-container ">
				<ul class="clearfix">				
					<li class="view"><?=CDates::getViewsText(@$data->views);?></li>
					<?php if($data->articlesAuthor && $data->articlesAuthor->author){ ?>
					<li class="author"><?=$data->articlesAuthor->author;?></li>
					<?php } ?>
					<?php /*
					<li class="author">Admin</li>
					<li class="comment">25 Comments</li>
					<li class="tag">Website Design - Responsive</li>
					*/?>
				</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="blog-item-text-container">
		<?php echo $data->{'anons'.DMultilangHelper::getPrefix()};?>
	</div>
	<div class="lp-r-m-container right">
		<a href="<?=$this->createUrl('/articles/view',array('alias'=>$data->alias));?>" class="button medium r-m-plus r-m-full">ЧИТАТЬ ДАЛЕЕ</a>
	</div>

</div>

protected/views/articles/blogaside.php
<aside class="blogaside fl">
	
	<?php if($model->idbanner1){ ?>
		<?php $banner = Banners::model()->findByPk($model->idbanner1) ?>
		<?php if($banner){ ?>
			<a href="<?=$this->createUrl($banner->link);?>">
				<img src="<?=Banners::model()->getPhotoNameUrl($banner->id.'.'.Yii::app()->getLanguage().'.jpg', $banner->timeupdate);?>" alt="<?=$banner->{'name'.DMultilangHelper::getPrefix()};?>">
			</a>
		<?php }?>
	<?php }?>
	
	<br>
	<br>
	<br>
	
	<?php if($model->idbanner2){ ?>
		<?php $banner = Banners::model()->findByPk($model->idbanner2) ?>
		<?php if($banner){ ?>
			<a href="<?=$this->createUrl($banner->link);?>">
				<img src="<?=Banners::model()->getPhotoNameUrl($banner->id.'.'.Yii::app()->getLanguage().'.jpg', $banner->timeupdate);?>" alt="<?=$banner->{'name'.DMultilangHelper::getPrefix()};?>">
			</a>
		<?php }?>
	<?php }?>
	
</aside>

protected/views/articles/index.php
<!-- PAGE TITLE -->
<div class="container m-bot-35 clearfix">
	<div class="sixteen columns">
		<div class="page-title-container clearfix">
			<h1 class="page-title">НОВОСТИ</h1>
		</div>	
	</div>
</div>	

</div>	<!-- Grey bg end -->	

<!-- CONTENT -->
<div class="container clearfix">
	<div class="twelwe columns m-bot-25">
		<?php
			if(!$dataProvider->getData()){
				echo '<div class="styled-box iconed-box error bold">Ничего не найдено по заросу "'.$_GET['searcharticlesname'].'"</div>';
			} else if(isset($_GET['searcharticlesname'])){
				echo '<div class="styled-box iconed-box info bold">Результаты поиска по запросу "'.$_GET['searcharticlesname'].'"</div>';
			}
		?>
	
		<?php 
			$countPage = ceil($dataProvider->getTotalItemCount() / $dataProvider->pagination->getPageSize());
			$pagenavi = "<div class=\"wp-pagenavi myPagenavi\">";
			if($countPage>1){
				$pagenavi .= "<span class=\"pages\">Страница ".(@$_GET['Articles_page']? $_GET['Articles_page'] : 1)." из ".($countPage)."</span>";
			}
			$this->widget('zii.widgets.CListView',array(
				'dataProvider'=>$dataProvider,
				'ajaxUpdate'=>false,
				'itemView'=>'_view',
				'pagerCssClass'=>'pagination-1',
				'template'=>"{items}{pager}",
				'pager'=>array(
					'class' => 'bootstrap.widgets.TbPager',
					'htmlOptions'=>array(
	        	'class'=>'pagination-1-container'
	        ),  
					'maxButtonCount'=>5,
					// css class
	        /*'firstPageCssClass'=>'hidden',//default "first"
	        'lastPageCssClass'=>'hidden',//default "last"
	        'previousPageCssClass'=>'pag-prev',//default "previours"
	        'nextPageCssClass'=>'pag-next',//default "next"
	        //'internalPageCssClass'=>'pager_li',//default "page"
	        'selectedPageCssClass'=>'pag-current',//default "selected"
	        'hiddenPageCssClass'=>'hidden'//default "hidden"*/
				)
		)); ?>
	
	</div>

</div>

protected/views/articles/view.php
<!-- PAGE TITLE -->
<div class="container m-bot-35 clearfix">
	<div class="sixteen columns">
		<div class="page-title-container clearfix">
			<h1 class="page-title">НОВОСТИ</h1>
		</div>	
	</div>
</div>	

</div>	<!-- Grey bg end -->	

<!-- CONTENT -->
<div class="container clearfix">
	<div class="twelwe columns m-bot-25">
		<!-- BLOG ITEM -->
		<div class="blog-item m-bot-35 clearfix">
			<div class="hover-item">
				<div class="clearfix">
					<div class="blog-item-date-inf-container left">
						<?php if($model->id != 1){ ?>
						<div class="blog-item-date-cont">
							<div class="blog-item-date"><?=date('d',$model->timework);?></div>
							<div class="blog-item-mounth"><?=CDates::getMounthMini(date('n',$model->timework));?></div>
						</div>
						<?php } ?>
						<div>
							<div class="blog-item-category-img">
								<img src="/images/icon-standart-post.png" alt="Ipsum" >
							</div>
						</div>
					</div>

					<div class="view view-first">
						<?php if($img = $model->getPhotoNameUrl($model->id.'.jpg', $model->timeupdate)){ ?>
							<img src="<?=$img;?>" alt="<?php echo $model->{'name'.DMultilangHelper::getPrefix()};?>" style="width:100%" >
						<?php } ?>	
						<?php /*
						<div class="mask"></div>							
						<div class="abs">
							<a href="<?=$img;?>" class="lightbox zoom info"></a>
							<a href="blog-single.html" class="link info"></a>
						</div>	
						*/?>
					</div>
				</div>	
				<div class="blog-item-caption-container">
					<div class="row">
						<div class="">
							<h1><span class="bold"><?php echo $model->{'name'.DMultilangHelper::getPrefix()};?></span></h1>
						</div>
						<div class="clear"></div>
						<div class="">
							<div class="blog-info-container">
								<ul class="clearfix">
									<li class="view in-blog"><?=CDates::getViewsText($model->views);?></li>
									<?php if($model->articlesAuthor && $model->articlesAuthor->author){ ?>
									<li class="author in-blog"><?=$model->articlesAuthor->author;?></li>
									<?php } ?>
								</ul>
							</div>
						</div>
						<div class="clearfix">
						<div class="caption-container-main">
							<div class="caption-text-container"><span class=""><?php echo $model->{'name2'.DMultilangHelper::getPrefix()};?></span></div>
							<div class="content-container-white caption-bg "></div>
						</div>
						</div>
						
					</div>

				</div>
			</div>
			<div class="blog-item-text-container clearfix">
				<?=$model->{'content'.DMultilangHelper::getPrefix()};?>
			</div>


		</div>
	</div>
</div>


<?php if($photoList){ ?>
<!-- CONTENT -->
<div class="container filter-portfolio clearfix">
	<ul id="portfolio" class="clearfix">
		<!-- PORTFOLIO ITEM -->
		<?php foreach($photoList as $data) { ?>				
		<li data-id="id-<?=$data->id;?>" data-type="category1" class="four columns m-bot-35">
			<div class="hover-item">
				<div class="view view-first">
					<?php if($img = Photos::model()->getPhotoUrl($data->id)){ ?>
					<a rel="photoList" href="<?=$img;?>">
						<img src="<?=$img;?>" alt="<?=$data->name;?>">
						<div class="mask"></div>	
					</a>
					<?php } ?>					
				</div>
				<?php /*<div class="lw-item-caption-container">
					<a class="a-invert" href="portfolio-single.html" >
						<div class="item-title-main-container clearfix">
							<div class="item-title-text-container">
								<span class="bold">Lorem</span> Ipsum
							</div>
						</div>
					</a>
					<div class="item-caption">web design</div>
				</div>*/?>
			</div>
		</li>
		<?php } ?>

	</ul>
</div>		

<?php } ?>


<!-- OUR PROJECTS End -->